install:
- sudo gem install pdd -v 0.20.5
assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  settings.xml: yegor256/home#assets/jcabi/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
install: |-
  sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  pdd --file=/dev/null
architects:
  - yegor256
  - andreoss
merge:
  script: |-
    mvn clean install -Pqulice --errors --settings ../settings.xml
deploy:
  script: |-
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Pjcabi -Pjcabi-http --errors --settings ../settings.xml
    # mvn clean site-deploy -Psite -Pjcabi --errors --settings ../settings.xml
