---
name: OWASP
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ master ]
jobs:
  owasp:
    name: Dependency-Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Maven
        run:  mvn --errors --batch-mode -Powasp dependency-check:check
